[tool.poetry]
name = "mortgage_madness"
version = "0.1.0"
description = ""
authors = ["Ben Warren <bwarren2@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
pandas = "^3.0.6"
jupyterlab = "^4.6.4"
matplotlib = "^3.11.2"
numpy-financial = "^1.0.0"
jupyter-black = "^0.4.0"
black = "^26.5.1"
plotly = "^7.1.0"
pandas-datareader = "^0.11.1"
ipywidgets = "^8.1.9"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
